apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-quss
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fxba-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-quss@sha256:35b840e2d6931b3d1d9040dfceeb7077d100539d18080e0e8650ab00b1c3adf2
        name: my-java-springboot
        resources: {}
status: {}
